---
stages:
  - build
  - promote

image:version:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: []
  script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_JOB_TOKEN}\"}}}" > /root/.docker/config.json
    - source "${CI_PROJECT_DIR}/version"
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile Dockerfile $DOCKER_PROXY --build-arg "VERSION=$VERSION" --destination "${CI_REGISTRY_IMAGE}:${IMAGE_VERSION:-VERSION}"
  only:
    variables:
      - $CI_REGISTRY_IMAGE

promote:version:
  stage: promote
  image: ananace/skopeo
  script:
    - source "${CI_PROJECT_DIR}/version"
    - /skopeo copy --src-creds "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" --dest-creds "${PROMOTE_USER}:${PROMOTE_PASS}" "docker://${CI_REGISTRY_IMAGE}:${VERSION}" "docker://${PROMOTE_IMAGE}:${PROMOTE_VERSION:-$VERSION}"
  when: manual
  only:
    refs:
      - master@serverdrift-projs/safesupport-bot
    variables:
      - $PROMOTE_USER
      - $PROMOTE_PASS
      - $PROMOTE_IMAGE

promote:latest:
  extends: promote:version
  variables:
    PROMOTE_VERSION: latest
